x-common-env: &common-env
  SERVER_SECRET: ${HULY_SECRET}
  SECRET: ${HULY_SECRET}
  STORAGE_CONFIG: minio|minio?accessKey=minioadmin&secretKey=minioadmin
  MONGO_URL: mongodb://mongodb:27017
  DB_URL: mongodb://mongodb:27017
  ACCOUNTS_URL: http://account:3000
  STATS_URL: http://stats:4900

services:
  mongodb:
    image: mongo:7-jammy
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - db:/data/db
    networks:
      - default

  minio:
    image: minio/minio
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - files:/data
    networks:
      - default

  elastic:
    image: elasticsearch:7.14.2
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - default

  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - default
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huly-rekoni.entrypoints=websecure"
      - "traefik.http.services.huly-rekoni.loadbalancer.server.port=4004"
      - "traefik.http.routers.huly-rekoni.rule=Host(`${DOMAIN}`) && PathPrefix(`/rekoni`)"
      - "traefik.http.routers.huly-rekoni.middlewares=huly-rekoni-stripprefix"
      - "traefik.http.middlewares.huly-rekoni-stripprefix.stripprefix.prefixes=/rekoni"
      - "traefik.http.routers.huly-rekoni.tls=true"
      - "traefik.http.routers.huly-rekoni.tls.certresolver=http-challenge"

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
      SERVER_PORT: 3333
      SERVER_CURSOR_MAXTIMEMS: 30000
      FRONT_URL: http://localhost:8087
      FULLTEXT_URL: http://fulltext:4700
      LAST_NAME_FIRST: true
    networks:
      - default
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      # WebSocket route
      - "traefik.http.routers.huly-transactor-ws.entrypoints=websecure"
      - "traefik.http.routers.huly-transactor-ws.rule=Host(`${DOMAIN}`) && PathPrefix(`/ws/transactor`)"
      - "traefik.http.routers.huly-transactor-ws.tls=true"
      - "traefik.http.routers.huly-transactor-ws.tls.certresolver=http-challenge"
      - "traefik.http.services.huly-transactor-ws.loadbalancer.server.port=3333"
      - "traefik.http.routers.huly-transactor-ws.service=huly-transactor-ws"

      # Strip WebSocket prefix
      - "traefik.http.routers.huly-transactor-ws.middlewares=strip-huly-transactor-ws-prefix"
      - "traefik.http.middlewares.strip-huly-transactor-ws-prefix.stripprefix.prefixes=/ws/transactor"

      # HTTP route for non-WebSocket traffic
      - "traefik.http.routers.huly-transactor.entrypoints=websecure"
      - "traefik.http.routers.huly-transactor.rule=Host(`${DOMAIN}`) && PathPrefix(`/transactor`)"
      - "traefik.http.routers.huly-transactor.tls=true"
      - "traefik.http.routers.huly-transactor.tls.certresolver=http-challenge"
      - "traefik.http.services.huly-transactor.loadbalancer.server.port=3333"
      - "traefik.http.routers.huly-transactor.service=huly-transactor"
      # Strip HTTP prefix
      - "traefik.http.routers.huly-transactor.middlewares=strip-huly-transactor-prefix"
      - "traefik.http.middlewares.strip-huly-transactor-prefix.stripprefix.prefixes=/transactor"

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
      COLLABORATOR_PORT: 3078
    networks:
      - default
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      # WebSocket route
      - "traefik.http.routers.huly-collaborator-ws.entrypoints=websecure"
      - "traefik.http.routers.huly-collaborator-ws.rule=Host(`${DOMAIN}`) && PathPrefix(`/ws/collaborator`)"
      - "traefik.http.routers.huly-collaborator-ws.tls=true"
      - "traefik.http.routers.huly-collaborator-ws.tls.certresolver=http-challenge"
      - "traefik.http.services.huly-collaborator-ws.loadbalancer.server.port=3078"
      - "traefik.http.routers.huly-collaborator-ws.service=huly-collaborator-ws"

      # Strip WebSocket prefix
      - "traefik.http.routers.huly-collaborator-ws.middlewares=strip-huly-collaborator-ws-prefix"
      - "traefik.http.middlewares.strip-huly-collaborator-ws-prefix.stripprefix.prefixes=/ws/collaborator"
      # HTTP route for non-WebSocket traffic
      - "traefik.http.routers.huly-collaborator.entrypoints=websecure"
      - "traefik.http.routers.huly-collaborator.rule=Host(`${DOMAIN}`) && PathPrefix(`/collaborator`)"
      - "traefik.http.routers.huly-collaborator.tls=true"
      - "traefik.http.routers.huly-collaborator.tls.certresolver=http-challenge"
      - "traefik.http.services.huly-collaborator.loadbalancer.server.port=3078"

      # Strip HTTP prefix
      - "traefik.http.routers.huly-collaborator.middlewares=strip-huly-collaborator-prefix"
      - "traefik.http.middlewares.strip-huly-collaborator-prefix.stripprefix.prefixes=/collaborator"

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
      SERVER_PORT: 3000
      TRANSACTOR_URL: ws://transactor:3333;wss://${DOMAIN}/ws/transactor
      FRONT_URL: http://front:8080
      MODEL_ENABLED: "*"
      ACCOUNT_PORT: 3000
    networks:
      - default
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huly-account.entrypoints=websecure"
      - "traefik.http.services.huly-account.loadbalancer.server.port=3000"
      - "traefik.http.routers.huly-account.rule=Host(`${DOMAIN}`) && PathPrefix(`/accounts`)"
      - "traefik.http.routers.huly-account.middlewares=huly-account-stripprefix"
      - "traefik.http.middlewares.huly-account-stripprefix.stripprefix.prefixes=/accounts"
      - "traefik.http.routers.huly.account.tls=true"
      - "traefik.http.routers.huly-account.tls.certresolver=http-challenge"

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
      TRANSACTOR_URL: ws://transactor:3333;wss://${DOMAIN}/ws/transactor
      MODEL_ENABLED: "*"
    networks:
      - default

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
      SERVER_PORT: 8080
      ACCOUNTS_URL: https://${DOMAIN}/accounts
      REKONI_URL: https://${DOMAIN}/rekoni
      CALENDAR_URL: https://${DOMAIN}:8095
      GMAIL_URL: https://${DOMAIN}:8088
      TELEGRAM_URL: https://${DOMAIN}:8086
      STATS_URL: https://${DOMAIN}/stats
      UPLOAD_URL: /files
      ELASTIC_URL: http://elastic:9200
      COLLABORATOR_URL: wss://${DOMAIN}/ws/collaborator
      TITLE: Huly Self Host
      DEFAULT_LANGUAGE: en
      LAST_NAME_FIRST: true
      DESKTOP_UPDATES_CHANNEL: selfhost
    networks:
      - default
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huly-front.entrypoints=websecure"
      - "traefik.http.services.huly-front.loadbalancer.server.port=8080"
      - "traefik.http.routers.huly-front.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.huly-front.tls=true"
      - "traefik.http.routers.huly-front.tls.certresolver=http-challenge"

  fulltext:
    image: hardcoreeng/fulltext:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
      FULLTEXT_DB_URL: http://elastic:9200
      ELASTIC_INDEX_NAME: huly_storage_index
      REKONI_URL: http://rekoni:4004
    networks:
      - default

  stats:
    image: hardcoreeng/stats:${HULY_VERSION}
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      <<: *common-env
      PORT: 4900
    networks:
      - default
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huly-stats.entrypoints=websecure"
      - "traefik.http.services.huly-stats.loadbalancer.server.port=4900"
      - "traefik.http.routers.huly-stats.rule=Host(`${DOMAIN}`) && PathPrefix(`/stats`)"
      - "traefik.http.routers.huly-stats.middlewares=huly-stats-stripprefix"
      - "traefik.http.middlewares.huly-stats-stripprefix.stripprefix.prefixes=/stats"
      - "traefik.http.routers.huly-stats.tls=true"
      - "traefik.http.routers.huly-stats.tls.certresolver=http-challenge"

networks:
  traefik-proxy:
    external: true
  default:

volumes:
  db:
  elastic:
  files:
